### ISSUE TITLE
Infografía-Daisy_Glez_Lita

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/infografia-de-hilos-Daisy-GonzalezLita12#2]
[Hilos_Daisy_Gonzalez_Lita (1).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Daisy-GonzalezLita12/files/15098791/Hilos_Daisy_Gonzalez_Lita.1.pdf)

**Comment by Nancy-0714** [comment]
Calificación: 20
Si cuenta con los criterios de la rubrica adecuadamente.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
